# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44b3ab60af96c0ea7639ba5cf5543ee893edcc76abac272f9d38716c082fc0585ec4be432b11facbc5a708ab955032a85c0c4b9b5bfcf15923c64a872baaef13

test:
  secret_key_base: 4b94eefef42737d98e68906e823fea0418c23b9d8b54b78deda573126c6104b5de21aff53553e9399daac0946c933f3b355cb499e9a29cef7b0f06f6fd68ff2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 75bd7480755ade9f5fb591ae54b0ead6a3ee1e1032c564cfa0290962db3a5ec6590d54d1f18dab737d74cb396b0e540bd8c0d6efd070d056a0ca9e07d0588718 %>
